# Site settings
title: Caitlin Meyer
description: "A blog on things library, tech, and more."
url: "http://www.caitlinmeyer.com"
author:
  name: "Caitlin Meyer"
  email: "caitlin.e.meyer@gmail.com"
  url: "http://caitlinmeyer.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
